### ISSUE TITLE
"Attempt to read past end of mangled string."

### ISSUE THREAD

**Issue by MonsterDruide1** [cmu-sei/pharos#118]
The following error occured at ~12 hours after the start of the analysis process:

![image](https://user-images.githubusercontent.com/26349348/86938173-68e30e80-c140-11ea-98e8-b3f6539ece4b.png)

I'm following the guide about Analysing large Executables, this error occured during step 2. I ran the following command: `ooanalyzer --serialize=ooprog.ser --maximum-memory 20000 --prolog-facts=ooprog-facts.P --threads=4 --per-function-timeout=10 libcocos2dcpp.so --verbose`
(Decreased "maximum-memory" to 20GB to stop Linux from killing the process, decreased the "threads" and decreased the "timeout" to speed up the process - If everything would have worked, I'd repeat the analysis with a higher timeout)

I'm trying to analyze `libcocos2dcpp.so` (12 MB), which is taken from the Android release of Geometry Dash. The `.exe` file from steam doesn't work too well, because the exe files drop all namings and all functions just have a default name.

The program seems to have found the end, as it sums up the function analysis, but then continues... Is it an issue specific for that file? Or does Pharos not work for linux libraries in general?

**Comment by sei-eschwartz** [comment]
This looks like a duplicate of #115.  Linux executables/libraries are not supported, and that is probably why the demangler is getting confused and throwing an exception.

**Comment by sei-ccohen** [comment]
OOAnalyzer is heavily focused on Windows 32-bit executables produced by Microsoft Visual Studio.  It is not likely to work well on Linux executables produced by GCC.  I'm a little surprised that you didn't get a warning about 64-but support being highly experimental.  Perhaps that is because this is a 32-bit EF executable? We should probably refuse to process non-PE executables just to be more clear about this.  We've previously permitted this so that people could experiment.  OOAnalyzer will do something, it's just not likely to be very useful.

There's also a problem with libraries in general, but it's more subtle.   In libraries, there are often a very large number of OO methods, but relatively few instantiations of actual objects.  Because tracking this-pointer data flow between methods on actual instantiations is the primary mechanism that OOAnalyzer uses to connect methods and discover classes, the lack of object instantiations can be a serious problem.   In general, OOAnalyzer performs much better on executables than libraries, although libraries that happen to instantiate lots of object instances would probably be fine.  An entire program packaged as a DLL would probably be fine for example.

As for the name demangling exception, someone else reported a similar problem just recently, and there may be a patch pending.

**Comment by MonsterDruide1** [comment]
Thanks for the quick responses! 
So if I understand this correctly, there is no simple way to make this work for Linux libraries? I took it from the `x86` folder, so probably that's why I didn't get the `64-bit warning`...
I could also analyze the windows executable instead, however I think that one's a 64 bit file. But it also wouldn't produce a useful outcome if I would apply the `.exe`-result on the `.so`-file... right?

**Comment by sei-ccohen** [comment]
Unless you also have a 32-bit PE executable (exe/dll), you're probably out of luck.    If there is a 32-bit Windows DLL, whether OOAnalyzer works correctly will be a function of what the actual program behavior is.   If there are lots of object instances in the DLL, you might be fine but usually, in libraries there are not (in my experience).

The results are very heavily tied to the specific executable that was analyzed (addresses of functions and so forth) so there's zero ability to apply results from one file to another, even if they're conceptually the same object oriented program.

**Comment by MonsterDruide1** [comment]
Okay... Thanks a lot anyways!
