### ISSUE TITLE
RTTI Information is invalid because missing self-reference for TDA

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#137]
```
RTTI Information is invalid because missing self-reference for TDA at address 0x69f0c0
RTTI Information is invalid because missing self-reference for TDA at address 0x6bcc28
RTTI was invalid.
```

Looks like there is a regression in RTTI handling as the same executable worked with older pharos versions with respect to RTTI.

https://github.com/cmu-sei/pharos/blob/1606c719fd766dd5bc3784254dfeef5681bdce00/share/prolog/oorules/rtti.pl#L234-L254

**Comment by sei-eschwartz** [comment]
Hmm, that's odd.  We did recently change some of the RTTI validation code, but I thought it was only more lenient.  I'll take a look at some of the changes and see if I can figure out what happened.

Could you share your exe, facts file, or even just the RTTI facts in the facts file?  Any of those could help.

**Comment by Trass3r** [comment]
Maybe it's not published yet? I'm using the latest docker image.
It's still this [testbed](https://github.com/Trass3r/pharosdata).

**Comment by Trass3r** [comment]
Ok so despite the missing TypeDescriptor and broken pVFTable pointers it looks like pharos is able to recover but of course can't associate a name:

```prolog
rTTITypeDescriptor(0x69efd8, 0x67bbdc, '.?AVCMovingThing@@').
finalVFTable(0x66d5bc, 0x94, 0x94, 0x66d5b8, '.?AVCMovingThing@@').
finalVFTable(0x66d4bc, 0x60, 0x60, 0, '').
```

**Comment by sei-eschwartz** [comment]
Great, we will look into this more.  Is there any reason to think the rtti data might be corrupted or modified?

Sent from Workspace ONE Boxer

On Sep 26, 2020 10:23 AM, Andreas Hollandt <notifications@github.com> wrote:

Ok so despite the missing TypeDescriptor and broken pVFTable pointers it looks like pharos is able to recover but of course can't associate a name:

rTTITypeDescriptor(0x69efd8, 0x67bbdc, '.?AVCMovingThing@@').
finalVFTable(0x66d5bc, 0x94, 0x94, 0x66d5b8, '.?AVCMovingThing@@').
finalVFTable(0x66d4bc, 0x60, 0x60, 0, '').

**Comment by Trass3r** [comment]
No I guess it was a compiler bug in msvc.

**Comment by Trass3r** [comment]
No I guess it was a compiler bug in msvc.

Ok I needed to go up to --verbose=5 to finally get a hint...
```
RTTI Class Hierarchy Descriptor was bad at 0x0069F0C0
RTTI Class Hierarchy Descriptor was bad at 0x006BCC28
```

**Comment by sei-ccohen** [comment]
Very interesting.  It took me a moment to figure out what happened here.   The "was bad at" error is being produced by the C++ code!   It's caused by a "catch(...) {}" in oosolver.cpp.   That in turn is preventing the required facts from being exported to Prolog, which is causing the RTTI facts to fail self-consistency checks in the Prolog phase.   For starters, that GDEBUG statement should probably be promoted to an ERROR level since it causes this confusing situation, but more importantly, we should figure out what exception in being thrown in C++.     One of your posts includes a null class name.   I suspect that might be related to the problem.    This could actually be a situation where the RTTI was modified to limit reverse engineering because I don't think the names are really used for much except debugging.

**Comment by Trass3r** [comment]
> It's caused by a "catch(...) {}" in oosolver.cpp. For starters, that GDEBUG statement should probably be promoted to an ERROR level since it causes this confusing situation, but more importantly, we should figure out what exception in being thrown in C++. 

Exactly, done that been there. Message is `Bytes not in image`.

**Comment by sei-ccohen** [comment]
That means that some pointer in one of the RTTI data structures ended up being a pointer to an address that wasn't in the program memory image.   If you can figure out which pointer that is, we can decide whether the problem is that the field was optional, whether the pointer really was invalid, etc.    The code currently expects that the entire "chain" of RTTI data structures will be valid and that such bad pointers won't occur.   It was intended as a validation mechanism so that we didn't report RTTI data structures for memory blocks that weren't in fact RTTI data structures.  The code throwing the exception is in read_bytes_strict() in memory.cpp, and the "expected pointers" are defined (rather cryptically perhaps) in the datatypes.hpp file.   We can look next week as well.

**Comment by sei-eschwartz** [comment]
```
OOAN[ERROR]: RTTI Class Hierarchy Descriptor was bad at 0x0069F0C0: read_bytes_script: request to read 4 bytes at 0x79685043 failed because some bytes were not found in the image
OOAN[ERROR]: RTTI Class Hierarchy Descriptor was bad at 0x006BCC28: read_bytes_script: request to read 4 bytes at 0x68436254 failed because some bytes were not found in the image
```

**Comment by Trass3r** [comment]
Looks like it's reading parts of the type descriptor name string as an offset.

**Comment by sei-ccohen** [comment]
So I finally tracked this down, and it was a tricky one!  This was an excellent bug to have found and squashed, so thank you very much for the report.

The problem was complicated by several bad error messages and an unfortunate coincidence.  One of the error message issues was corrected above, involving the lack of detail about which address was invalid.   But the error is still a little misleading because the problem isn't in the ClassHierarchyDescriptor (CHD), it's in one of the BaseClassDescriptors (BCD), referenced from the CHD.   that's because a rather large block of code is wrapped in the try.    Additionally, the problem isn't in the SelfRef checks, it's just the TypeDescriptor at  0x69f0c0 was missing.  That bad error message looks like it was a cut-and-paste error in rtti.pl.

Finally, the coincidence (which might not be entirely random, but was still very much _unexpected_) was the multiple conflicting uses of 0x69f0c0 in the problem.  Notice that the error complains that the ***CHD*** at this address is invalid.   Well of course it is.  That address is a TypeDescriptor, not a CHD.  But that's a little hard to figure out because the real bug is that the TypeDescriptor is missing (and not reported clearly as such in the error).  Why is there so much confusion over this particular address?

Coincidentally (?), it happens to be the DWORD immediately following a BCD that does ***NOT*** have the optional BaseClassHierarchyDescriptor (BCHD) points to 0x69f0c0.   The BCHD is an undocumented feature that we've been reverse engineering for a while now, and we've rather recently discovered that is controlled by but 0x40 in the BCD attributes field.   We've been a little lazy about this optional field, always reading it from memory, and reporting it during fact exporting as if it always exists.   Then we sort out in Prolog whether it _really_ exists.   In this particular case, the fact that the DWORD in question happened to point to another valid RTTI data structure led to all of these unexpected consequences.

This probably explains why the bug manifesting in this way was relatively rare.  Unfortunately, I think that the more common behavior was to just to declare certain RTTI objects invalid an exclude them silently. :-(   The fix which will be public soon is to check for 0x40 before assuming the BCHD exists, and attempting to export it.  This will prevent the address from being added to the list of already exported RTTI data structures, which will allow the correct TypeDescriptor to be exported.  Whew!

**Comment by Trass3r** [comment]
That change does produce 2 new rTTITypeDescriptors as expected but then `ooprolog --log-level=3 --facts facts.pl --results results.pl` fails for me:
```
Consistency checks failed.
Contradictory information about merging classes: Method1=0x66cb4c Method2=0x66fbcc
Initial sanity check failed, indicating the OO rules are incorrect.
```

**Comment by sei-eschwartz** [comment]
Going to track this new problem in #139 since this issue (RTTI facts) was fixed

**Comment by Trass3r** [comment]
> Though only now it occurs to me that the pVFTable pointers are the same for all types (pointing to the `type_info` vtable). Odd.

> I guess it was a compiler bug in msvc.

It's not it seems: https://godbolt.org/z/9qWGsc

**Comment by sei-ccohen** [comment]
Just because I get confused about which ticket is which when multiple people find the same problems independently, I wanted to make sure that you had seen this [comment](https://github.com/cmu-sei/pharos/issues/136#issuecomment-700180608), which is what actually prompted my change in the code (Prolog fact documentation) about this.
