### ISSUE TITLE
Optionally allow include-func to traverse into sub-routines

### ISSUE THREAD

**Issue by SK83RJOSH** [cmu-sei/pharos#145]
I'm currently working with an x64 executable with a lot of complexity and some behemoth functions that cause ooanalyzer to grind to a halt. I'm uncertain as to why, but it actually appears to get stuck in a loop and rapidly consumes a whopping 256GB of RAM while analyzing. I'm not particularly sure why this is, but after the 5th OOM I decided to exclude some bigger functions from analysis. My hope was that I would be able to do separate runs for those problem functions to pull out all the constructor calls contained therein as these functions are file loaders and are the only place many objects are instantiated. Unfortunately it seems that using `--include-func` means I need to manually tag all of the sub-routines within as included functions as well... which isn't trivial or ideal.

So I was wondering if it's possible to change the behavior of include-func to allow ooanalyzer to kick off jobs analyzing any referenced functions contained within the target function? Perhaps with a configurable stack depth to allow preserving the existing behavior while also adding some major gains in flexibility? This would allow me to debug the hang as well as split up the analysis of this executable and manually reconcile the resulting databases.

Unrelated questions:

Do you have any recommendations for tuning ooanalyzer to be a bit less crazy with memory that can give decent results for these kinds of cases?

> It's been very hit or miss in terms of memory consumption for me. I've found the the per-function-timeouts as well as memory limits seem to randomly not apply, or randomly kick in for a method that's well below all limits I've supplied. I'm not sure if this is down to issues with x64 support in general, or if my executable is doing something to confuse the analyzer. Could very well be a bug in the limits code, though I didn't see any obvious issues when I reviewed the source.

Do you have any strategies/tips for combining information from multiple databases extracted from the same executable?

> My first run got a lot of objects the second didn't, likely because I had a lower `per-function-timeout` and hadn't excluded those behemoth file loaders. The second run successfully identified new ctors, dtors, classes, and a lot of new members and methods. It would be great to be able to combine those two databases either with manual or programmatic conflict resolution. I understand that there may be some inaccuracies, but given I can't run a full analysis I see no other way proceed with an executable like this.

Is it unheard of for there to be functions causing analysis to halt like this?

> My executable is around 4MB and analysis seems to progress normally up until the point it reaches 99% analysis. At this point it ends up hammering a single core traversing one of the larger routines indefinitely. Seems to get tripped up somewhere and just start allocating memory like crazy with no console output whatsoever. It appears to also ignore the timeout + memory limits I've set. It's impossible for me to even attempt to debug this at the moment due to the prohibitive amount of memory needed to even reach that stage in the process. It took about 20 minutes, 16-cores, and 80GB of RAM before reaching that point in the analysis -- and unfortunately I can't justify paying for that VM to attempt to triage this any further. I can provide a sample and my configuration privately upon request -- but I cannot distribute it on Github.

**Comment by sei-eschwartz** [comment]
This sounds like a bug to me.  If you have reasonable limits set, you shouldn't be seeing this type of behavior.  Can you please email your executable and configuration to `eschwartz@cert.org`?

Just so you know, OOAnalyzer will allow you to run on x64 binaries, but the rules are only written for 32-bit VC++ binaries.  You should have very low expectations for the results.

> Do you have any strategies/tips for combining information from multiple databases extracted from the same executable?

No, there is no way to do this.  It would be better to fix the underlying problem.

**Comment by sei-ccohen** [comment]
As sei-eschwartz commented, OOAnalyzer doesn't really support 64-bit executables, so you should not expect much on this executable.  In particular, I'm skeptical of of the merits of paying for a VM for analysis in this case. 

We'll be able to best understand what's happening if we can see the problem ourselves, but your comment about stopping at 99% strongly suggests to me that you're actually in the function partitioning phase, and not the function analysis phase.   This progress bar has lines that being PRT2. There's some [documentation](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules) on how to run large files that may be of interest to you.  Being stuck at 99% is usually caused by our custom partitioning extensions, and --partitioner=rose is the most likely fix.  I general, the memory and timeouts are not properly respected during the partitioning phase, because they're a Pharos extension to the ROSE compiler framework, and we've had to tap into that code to impose the limits as best as we can.

We do not have any way to combine result files, because the Proloig rules for producing results are very dependent on the interaction of all of the facts.   

The --per-function-timeout only applies during the function analysis phase and is intended to prevent cases where very large single functions consume excessive RAM and memory.  If you really are having a problem in the function analysis phase, there's a chance that we've made a code block out of a very large number of zeros, or other data resulting in "garbage" instructions.  The intention was that --exclude-function could be used to explicitly disable the functions that were causing the problems, although admittedly for very large programs with lots of bad functions this will not be convenient. :-(   The --serialize option will be your friend here.  Turning on the --verbose option will announce each function analysis allowing you to see which ones are taking a long time.

**Comment by SK83RJOSH** [comment]
>As sei-eschwartz commented, OOAnalyzer doesn't really support 64-bit executables, so you should not expect much on this executable. In particular, I'm skeptical of of the merits of paying for a VM for analysis in this case.

I'm about to email the executable in question, though I wanted to point out that the VM was relatively inexpensive through AWS and it was a fun exercise. The result I got were quite good actually, just incomplete, and I'd like to give it another go in the future. It's just that I was not able to triage this issue without significant time investment on my part. 👍 

>We do not have any way to combine result files, because the Proloig rules for producing results are very dependent on the interaction of all of the facts.

Understood, in my case I wanted to merge the missing classes from one into the other, and update the names of a few classes that were determined to be constructors in the latest run. I verified the results and they were indeed correct. Though I completely understand, I can write a script to do this, it's rather specific to my botched attempt at analysis.

>If you really are having a problem in the function analysis phase, there's a chance that we've made a code block out of a very large number of zeros, or other data resulting in "garbage" instructions. 

Likely the case, I had to run with --mark-executable due to a lot of executable code being missed. I suspect this could be the culprit, but I'm uncertain.

>We'll be able to best understand what's happening if we can see the problem ourselves, but your comment about stopping at 99% strongly suggests to me that you're actually in the function partitioning phase, and not the function analysis phase. This progress bar has lines that being PRT2. 
I never got any logs indicating this. Log below. 😢 

>The --serialize option will be your friend here. Turning on the --verbose option will announce each function analysis allowing you to see which ones are taking a long time.

Wasn't aware of `--seralize`, I'll give that a go to speed things up. I enabled the verbose option, but unfortunately my final output before ooanalyzer rapidly consumed all system memory seemed to indicate it succeeded:
![image](https://user-images.githubusercontent.com/1371787/98019664-52a14280-1e02-11eb-80ce-c8f2ce2e62b7.png)

**Comment by sei-ccohen** [comment]
Very interesting.  You seem to be in good command of the issues.  You are indeed stuck in function analysis and not partitioning.   I strongly suspect that your --mark-executable options are somehow related, but I'm at a bit of a loss for exactly how.  You've probably identified some bug that we've not really seen before.

As for the 64-bit analysis being (in)correct, the primary problem is that some key facts are inappropriately restricted to the 32-bit __thiscall calling convention, and as a consequence we won't export facts that are required to reach correct answers.  I don't know if we've ever really thought about how many wrong answers (versus incomplete) that produces.    I'm gald to hear that you're getting value from it.   I tend to think it does useful things, and my colleagues tend to point out that I have no real evidence for that. :-| I see that your log detected 0x140014BE0 as __thiscall.  I wonder if that's correct.   Do you have 32-bit calling conventions in your 64-bit code for some reason, or is that maybe just the detection of a normal 64-bit ABI calling convention that happens to be passing a valie in RCX?

We do process functions in a [https://github.com/cmu-sei/pharos/blob/master/libpharos/bua.cpp#L274](bottom up order), and a longish-delay with a single processor being active is the usual way that code completes, but it shouldn't take more than the the per function timeout for each function.  There are sometimes a few functions right at the end that each get processeed serially on after an another.  A long complex recursion chain is often involved -- we ultimately just snip the recursion cycle arbitrarily at one of the functions, and perhap we're not choosing well.

Finally, if you're really determined to try and merge analyses, I suggest merging the fact files, doing some edit/grep/uniq as required, and then re-running the Prolog analysis phase for the best results.   The facts involving symbolic values (sv_xxx) are likely to be all screwed up from separate runs, but it's unclear how harmful that will be.   You're getting pretty deep into the internals now, but conceptually you should be able to improve the results by encoding some of your manually determined knowledge into the fact file, for example by removing facts for functions that generating wrong answers and so forth.

In general, reverse engineering large OO programs is a huge undertaking even with the assistance of a tool like OOAnalyzer which makes it very obvious how much more work we have to do before the results are completely correct. :-(

**Comment by SK83RJOSH** [comment]
>Very interesting. You seem to be in good command of the issues. You are indeed stuck in function analysis and not partitioning. I strongly suspect that your --mark-executable options are somehow related, but I'm at a bit of a loss for exactly how. You've probably identified some bug that we've not really seen before.

Well I had some time to dig through the ooanalyzer source and make some educated guesses. Granted who knows for certain! :)

>As for the 64-bit analysis being (in)correct, the primary problem is that some key facts are inappropriately restricted to the 32-bit __thiscall calling convention, and as a consequence we won't export facts that are required to reach correct answers. I don't know if we've ever really thought about how many wrong answers (versus incomplete) that produces. I'm gald to hear that you're getting value from it.

Quite a bit of use actually, it's successively identified a myriad of member functions, initializers, dtors, ctors, and so on. Though I haven't combed through everything of course. From what I've seen so far, it's done a surprisingly good job. Definitely will save me a lot of hassle annotating all of these myself. I'll be on the look out for any obvious errors in analysis and report back sometime in the future perhaps. 👍 

>I see that your log detected 0x140014BE0 as __thiscall. I wonder if that's correct. Do you have 32-bit calling conventions in your 64-bit code for some reason, or is that maybe just the detection of a normal 64-bit ABI calling convention that happens to be passing a valie in RCX?

This is a C++ executable, which I guess rather luckily, will always pass the `this` pointer via `RCX` using the x64 __fastcall convention. In this case it is indeed correct it seems, it's actually called by a constructor a few functions down from WinMain.

>We do process functions in a [https://github.com/cmu-sei/pharos/blob/master/libpharos/bua.cpp#L274](bottom up order), and a longish-delay with a single processor being active is the usual way that code completes, but it shouldn't take more than the the per function timeout for each function. There are sometimes a few functions right at the end that each get processeed serially on after an another. A long complex recursion chain is often involved -- we ultimately just snip the recursion cycle arbitrarily at one of the functions, and perhap we're not choosing well.

My per function time out was 20 minutes in this case, as I was attempting to get as complete of a picture as possible, and it was very close to chewing through nearly every function of interest in this program. That said, I'm not sure if it got killed by OOM before the function timeout, but I'm not certain. In fact, it went over the global memory limit I set... I was certain to set it low enough that OOM wouldn't kill it. :/

>Finally, if you're really determined to try and merge analyses, I suggest merging the fact files, doing some edit/grep/uniq as required, and then re-running the Prolog analysis phase for the best results. The facts involving symbolic values (sv_xxx) are likely to be all screwed up from separate runs, but it's unclear how harmful that will be. You're getting pretty deep into the internals now, but conceptually you should be able to improve the results by encoding some of your manually determined knowledge into the fact file, for example by removing facts for functions that generating wrong answers and so forth.

That might be too deep in the internals for me, though I may consider doing a deep dive if this issue isn't resolvable. Could be a fun exercise.

>In general, reverse engineering large OO programs is a huge undertaking even with the assistance of a tool like OOAnalyzer which makes it very obvious how much more work we have to do before the results are completely correct.

It absolutely is it indeed. I've done manual reversing of a few extremely large programs, but it's usually only for functions / objects of interest. I work in the games industry, and it's fun to dig into other peoples work for inspiration from time to time -- and on occasion -- patch in some fun modifications. :)

**Comment by sei-ccohen** [comment]
So I finally got around to testing this more thoroughly.  Your script had a very reasonable set of command-line options.  My serialization file was 288MB, and loads in about 100 seconds.  I forgot to capture how long the partitioning took. :-(  My partitioning reported:

Partitioned 3116824 bytes, 756935 instructions, 189037 basic blocks, 11603 data blocks and 18140 functions.

Using --mark-executable is probably the cause of those messages about instruction successors not being found, but there's only 145 of those so it doesn't seem too bad.  They're mostly in a couple of address ranges, so there was clearly some bad disassembly, but I don't think that's the root cause of whatever problems you're encountering.

All of the messages about "Unrecognized 64-bit calling convention: __stdcall" and "No stack delta information for" are because our API database is specifically targeted at 32-bit executables.  In theory, all of the 64-bit calls are stack neutral so it shouldn't matter.

As for the primary problem of getting "stuck" late in the analysis, it's hard to compare performance on different systems, but I didn't find anything too abnormal.  My latest theory is that RAM shortages are the problem.  After running with your options, I ran again with --maximum-memory=0 (unlimited).    With --threads there's really no way for us to implement the --per-function-maximum-memory feature.  We normally inspect total process memory and when OOAnalyzer is single threaded, we know which function to blame.  With --threads, we do not.  I'll contrast some of the differences in results below.

Your options (with -threads=24 and some other minor filename changes) results in 155896 Prolog facts and 1994 Prolog Results on my system.  With unlimited RAM, there were 189117 Prolog facts, and 3816 Prolog results.   Not badd for a completely unsupported architecture. :-)  By grepping for "absolute" I was able to see that at around 956 seconds, I ran out of RAM with your options, and by 1053 seconds I was finished analyzing functions.  With unlimited RAM, no functions failed due to the memory limits.

When the RAM limit was removed, function analysis progressed steadily for about 1600 seconds.  At this point I was using ~35GB of RAM, and had processed almost 18000 of the 18140 functions. The last 140 functions took about 550 seconds to complete, and caused memory consumption to grow dramatically to about 65GB.  But by 2150 seconds function analysis had completed, and Prolog analysis had begun and OOAnalyzer completed successfully at 2264 seconds.     Whatever is going on that needs 30GB and 550 seconds for 140 functions isn't great, but it's not terribly surprising either.  A variety of bad things can happen during symbolic analysis, including many scenarios that cause fairly explosive memory growth.   That's why we have per function time and memory limits. :-)  

There's a couple of ways you can work around this if more memory is not a solution for you.  One is to figure out what the last  ~140 functions are and --exclude them.   Another is to set the --per-functon-timeout to something smaller, giving them less time to gobble up RAM.   Finally, foregoing --threads will allow you to set a per function memory limit that actually works.   In my unlimited memory run, with your 2000 second per function timeout, grepping for "timeout" revealed that I had 52 functions that did not complete analysis.

So hopefully that gives you enough information to complete your analysis.
