### ISSUE TITLE
Contradictory information about constructor

### ISSUE THREAD

**Issue by dimitrijejankov** [cmu-sei/pharos#172]
The prolog phase fails during backtracking, for the attached files
https://drive.google.com/file/d/17_oDVPboGUULuW4hajL4ywnJehgazx9L/view?usp=sharing

**Comment by sei-eschwartz** [comment]
The error is that we can't figure out if 0x6648e0 is a constructor or destructor.  It looks like `BZ::CSteamStorage::CSteamStorage` to me.

We guess that it is a constructor, but this leads to a contradiction for 0x6661f0:

`Contradictory information about constructor: factConstructor(0
x6661f0) but reasonNOTConstructor(0x6661f0)`

It looks to me like 0x6661f0 is `BZ::CSteamStorage::~CSteamStorage`, which we guess is a constructor (incorrectly) because of guessConstructor1.

So this looks like a guess prioritization issue.

**Comment by sei-eschwartz** [comment]
The other thing I noticed is that OOAnalyzer is not using RTTI information:

```
RTTI was present, found 5,653 predicates.
RTTI Information is invalid because InheritsDirectlyFrom P = 0x4
RTTI Information is invalid because InheritsDirectlyFrom V = 0x4
RTTI was invalid.
```

At least in IDA the RTTI looked fine though.  @sei-ccohen should look into this.  @dimitrijejankov you may want to try commenting out this line to avoid the failing check:

https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/rtti.pl#L270

But don't comment out the trailing `],`.  This will hopefully allow the RTTI to be used, and might bypass the problem you encountered.

**Comment by sei-eschwartz** [comment]
Line 269 has to be commented out as well

**Comment by dimitrijejankov** [comment]
I did a run with just 270 commented out, still the same problem. I will try 269 too :)

**Comment by cfcohen** [comment]
So with the RTTI checks commented out, we definitely accepted and used the RTTI which is nearly certain to substantially change the results.  After running about 3 hours we're still guessing VBTables, so it'll be a little longer to see if it makes it further than the previous run.  There's now some confusion about whether 0xa69740 is a constructor, and whether 0x1d4c3f0 is a virtual base table (I think pretty clearly it is, although OOAnalyzer was forced to conclude that it was not due to a contradiction).

I took the task of understanding why we thought the RTTI was invalid.  It seems that the problem is caused by a combination of multiple inheritance and virtual inheritance combined.  Since both multiple inheritance and virtual inheritance are a little complicated in binaries, it's not shocking that we have some issues when they're combined.   The following RTTI Base Class Descriptors would have failed validation:

```
rTTIBaseClassDescriptor(0x1d6913c, 0x1e01720, 0x1, 0, 0, 0x4, 0x40, 0x1d69350).
rTTIBaseClassDescriptor(0x1d69158, 0x1e0173c, 0, 0x8, 0, 0x4, 0x40, 0x1d69318).
rTTIBaseClassDescriptor(0x1d74150, 0x1e0d0c8, 0x1, 0, 0, 0x4, 0x40, 0x1d74294).
rTTIBaseClassDescriptor(0x1d74134, 0x1e01790, 0, 0, 0, 0x4, 0x40, 0x1d693e0).
rTTIBaseClassDescriptor(0x1d7f7a0, 0x1e16900, 0, 0, 0, 0x4, 0x40, 0x1d7f11c).
rTTIBaseClassDescriptor(0x1d7f898, 0x1e16900, 0, 0, 0x8, 0x4, 0x40, 0x1d7f11c).
rTTIBaseClassDescriptor(0x1d7fbf8, 0x1e16900, 0, 0, 0x4, 0x4, 0x40, 0x1d7f11c).
```

Because the BCD flags of 0x40 say that there is NOT virtual inheritance (marked by bit 0x50).  The two values immediately before the flags named P & V, and are documented [here](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/facts.pl#L99) as the member displacement and the vtable displacement.  We expect these to be -1 and 0 when the virtual inheritance flag is not set.  It appears that the scenario that we hadn't anticipated was virtual inheritance in the second base class... (I think).

Fortunately for us (and you too), the names reference publicly available source code, so we should be able to sort out what the correct thing to do is.   The inheritance hierarchy for the last unexpected fact is:

```
class X509PublicKey : public ASN1CryptoMaterial<PublicKey> {}
  https://cryptopp.com/docs/ref/asn_8h_source.html#l00701
  rTTITypeDescriptor(0x1e16c08, 0xd13688, '.?AVX509PublicKey@CryptoPP@@', 'CryptoPP::X509PublicKey').

class ASN1CryptoMaterial<BASE> : public ASN1Object, public BASE {}
  https://cryptopp.com/docs/ref/asn_8h_source.html#l00683
  Defines two methods only (Load and Save)
  rTTITypeDescriptor(0x1e16898, 0xd13688, '.?AV?$ASN1CryptoMaterial@VPublicKey@CryptoPP@@@CryptoPP@@', 'CryptoPP::ASN1CryptoMaterial<class CryptoPP::PublicKey>').
  
Class ASN1Object {}
  https://cryptopp.com/docs/ref/cryptlib_8h_source.html#l03283
  rTTITypeDescriptor(0x1e17434, 0xd13688, '.?AVASN1Object@CryptoPP@@', 'CryptoPP::ASN1Object').

class PublicKey : virtual public CryptoMaterial {}
  https://cryptopp.com/docs/ref/cryptlib_8h_source.html#l02535
  No methods
  rTTITypeDescriptor(0x1e16874, 0xd13688, '.?AVPublicKey@CryptoPP@@', 'CryptoPP::PublicKey').

class CryptoMaterial : public NameValuePairs {}
  https://cryptopp.com/docs/ref/cryptlib_8h_source.html#l02389
  rTTITypeDescriptor(0x1e16f54, 0xd13688, '.?AVCryptoMaterial@CryptoPP@@', 'CryptoPP::CryptoMaterial').

class NameValuePairs {}
  https://cryptopp.com/docs/ref/cryptlib_8h_source.html#l00321
  rTTITypeDescriptor(0x1e16900, 0xd13688, '.?AVNameValuePairs@CryptoPP@@', 'CryptoPP::NameValuePairs').
```

The conclusion we derived from RTTI that was flagged as invalid was:

```
rTTIInheritsDirectlyFrom(0x1e16c08, 0x1e16900, 0x3, 0, 0x4, 0x4)
```

Which says that X509PublicKey inherited directly from NameValuePairs (incorrect).   We almost certainly won't know what to make of the non-zero values for P & V in this situation.  The next test should probably be to conclude rTTIInheritsDirectlyFrom only when P = -1, and V = 0, preventing the incorrect rTTIInheritsDirectlyFrom conclusions.   My guess is that this is related to why we're still confused about the virtual base table at 0x1d4c3f0 in the current run.  That would essentially discard the incorrect conclusions, rather than accepting them as the current approach does.   Figuring out how to correctly reason about both virtual and multiple inheritance at the same time requires rather more thought...

**Comment by cfcohen** [comment]
By the way, at more than a million facts and a 28MB input executable plus some complex multiple/virtual inheritance, this file is likely to be challenging for OOAnalyzer.  There's a good chance that we'll get it to run to completion, but because of the time it takes to complete a single test cycle, it probably will take a while to figure it out.

**Comment by sei-eschwartz** [comment]
Here is my rough idea for how we should reason about this situation:

0x6648e0 is probably a constructor because it calls the base constructor before installing a vftable.
Because 0x6648e0 calls 0x666120, it's likely a constructor.
0x6661f0 is probably a destructor because it installs a vftable before calling the base destructor.
Because 0x6661f0 calls 0x666260, it's likely a destructor.

We don't have a rule for this, because I think in many situations the base constructors are inlined.  But in cases like this, we should start guessing at the child constructors and destructors because the order of calls and vftable installations is suggestive.

**Comment by sei-eschwartz** [comment]
I am testing a branch based on this idea.  We are running into #169 though... so trying to work around that.

**Comment by sei-eschwartz** [comment]
Good news.  We've been making a lot of changes to get your file to work.  Both performance changes and a solution to #169 and some other things.  The bad news is that the changes aren't public yet.  We'll release them soon after a bit more testing.  But in the meantime, I was able to get a run of your program to complete: 
[magicduels.zip](https://github.com/cmu-sei/pharos/files/6336178/magicduels.zip)

I have not looked at these results at all.  If something does not seem right please let us know.
