### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#18]
Has anyone ever tried to compile it for Windows?

**Comment by sei-ccohen** [comment]
We have not due to the complexities of getting the ROSE dependency to build on Windows.  The ROSE developers have successfully built ROSE for Windows, and if ROSE builds, we suspect that Pharos would build as well.   We have successfully built Pharos for MacOS with clang a couple of times, but it's a bit fragile. We'd be very interested in hearing about your results if you attempt either.

**Comment by Trass3r** [comment]
I thought so. Wouldn't attempt to compile it honestly, rather using WSL.

**Comment by rokups** [comment]
Compilation is a problem even on linux. I tried to make Z3 and Rose to be built by cmake together with pharos but did not have much success. Not that it is not possible, but definitely would be time consuming. Which is very unfortunate.

**Comment by sei-ccohen** [comment]
Compiling on Windows is definitely a longer term goal that was already on the todo list, but isn't being prioritized for significant effort right now.   Rather than leave this issue open for many months (or longer) I'm going to close it.  The new release should build correctly on MacOS (although I haven't actually tried it yet).  And conceptually, everything could/should build on Windows as well, so if anyone even tries, please let me know what you encountered.  If anyone succeeds or even gets close, I'll be very open to making whatever changes are required to support that.
