### ISSUE TITLE
no warning for missing API functions

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#21]
As soon as there is a single function declaration for a particular dll in your json DB it does not warn anymore for any other missing functions. Not sure if that's intended.
(Also, is there a tool to generate a json db from header files?)

**Comment by Trass3r** [comment]
Also it doesn't print any errors if types that are probably unknown are used, like LPDIRECTDRAW in this case:
```json
{
	"dll": "DDRAW.DLL",
	"export_name": "DirectDrawCreate",
	"display_name": "DirectDrawCreate",
	"convention": "stdcall",
	"parameters": [
		{
			"name": "lpGUID",
			"type": "GUID*",
			"inout": "in"
		},
		{
			"name": "lplpDD",
			"type": "LPDIRECTDRAW*",
			"inout": "out"
		},
		{
			"name": "pUnkOuter",
			"type": "IUnknown*",
			"inout": "in"
		}
	],
	"type": "HRESULT"
},
```

**Comment by cfcohen** [comment]
Because there can be a very large number of imports for each DLL, which can generate a large number of errors, we made the decision to only report the missing DLL where there is no data for the DLL.  I think that once you've defined a single function for a given DLL, the remainder of the missing functions will be reported.

Right now the actual types aren't used by the Pharos system.  We have some experimental type analysis code that is disabled by default due to performance issues that can conceptually use those types, and we hope to make better use of them in the future.  In practice the parameters are just there right now to get a correct parameter count, and therefore a correct stack delta for the function.

**Comment by Trass3r** [comment]
> I think that once you've defined a single function for a given DLL, the remainder of the missing functions will be reported.

Doesn't match what I experienced.

> Right now the actual types aren't used by the Pharos system. We have some experimental type analysis code that is disabled by default due to performance issues that can conceptually use those types, and we hope to make better use of them in the future. In practice the parameters are just there right now to get a correct parameter count, and therefore a correct stack delta for the function.

Ha ok.

**Comment by sei-mwd** [comment]
I've been looking though the ReportDictionary code in apidb.[cpp,h] that I wrote to handle this.  I haven't found out what this might be via inspection, however.  I'll do some testing a little later, but I think the warnings you want might be hidden at a lower level of logging.  Please try with --log="APID(all)" to get all the gruesome details on what is actually being lookup up and from where, under the hood.

**Comment by sei-ccohen** [comment]
Did the additional logging resolve this issue?  Did the new release?  If this problem still occurs, please attempt to provide a small test case that demonstrates the problem and we'll fix it.  Internally we're agreed that it's supposed to have reported one error for the entire DLL when there's no data at all for that DLL, and report an error for each function individually where there is data for the DLL.  The API database system is fairly complex and multi-layered, so it's possible that you've found something that we've just missed.
