### ISSUE TITLE
Lots of error "OOAN[ERROR]: update_return_values, no output state for 0x004CFC00"

### ISSUE THREAD

**Issue by lcytxw** [cmu-sei/pharos#24]
I don't know what this error means. The software I tested can be download from the link blow: 

https://drive.google.com/file/d/1VgdH0IJguqLjyT_m-b-CCHAN9slbZ4Yk/view?usp=sharing

icy@ubuntu:$ ooanalyzer  -j yundetectservice.json yundetectservice.exe 
OPTI[INFO ]: Analyzing executable: yundetectservice.exe
OPTI[INFO ]: OOAnalyzer version 0.13.
OPTI[INFO ]: ROSE stock partitioning took 314.121 seconds.
OPTI[INFO ]: Long delays until the next time stamp are caused by the Pharos custom partitioning
OPTI[INFO ]: algorithm and may be resolved by using the --stockpart option, but at the expense
OPTI[INFO ]: of possibly less complete function detection.  Using --no-semantics may also help.
OPTI[INFO ]: Function partitioning took 2117.42 seconds.
OAN[ERROR]: update_return_values, no output state for 0x00401000
...
OOAN[ERROR]: update_return_values, no output state for 0x004CFC00
OOAN[ERROR]: No new() methods were found.  Heap objects may not be detected.
OOAN[ERROR]: No delete() methods were found.  Object analysis may be impaired.
OPTI[INFO ]: Function analysis complete, analyzed 6037 functions in 49.2624 seconds.
OPTI[INFO ]: Successfully exported to JSON file 'yundetectservice.json'.
OPTI[INFO ]: OOAnalyzer analysis complete.

**Comment by Trass3r** [comment]
Did you run into a timeout?

**Comment by sei-ccohen** [comment]
This message is admittedly poor.   What's really happening here is that we tried to analyze a function, and for whatever reason, it didn't produce the expected output state summarizing the function behavior.   Timeouts are the most common cause, but not the only cause.  Memory limits and some other unexpected conditions can also result in this error.  If there are many such messages, that's almost always a whole program timeout issue.  We should probably alter the code to detect that the CPU limit was exceeded and change the message as a result, but this turns out to be rather inconvenient. (pull requests anyone?)

If there's a small number of these messages (for example because of the per-function timeout) you should decide whether the listed functions are important to you, and if they're not, you can safely ignore the messages.  If they are...  well that's where things get complicated. ;-)

**Comment by lcytxw** [comment]
Solved
