### ISSUE TITLE
Partitioner stucks at 17 % and often gets killed

### ISSUE THREAD

**Issue by Maxxxel** [cmu-sei/pharos#245]
Here are my Specs:
- CPU Ryzen 9 5900HX
- GPU RTX 3080
- RAM 32 GB DDR4
- 2x 1 TB SSD

The Executable im trying to analyze is ~26 MB in size.

My command is: 
```
partition --serialize=file.ser --maximum-memory=128000 --no-semantics file.exe
```

Thats my .wslconfig (as suggested by @YamamotoKaderate here https://github.com/cmu-sei/pharos/issues/243#issuecomment-1340034671)
```
swap=245GB
cgroup_disable=memory
```

What it does so far:
- It starts to run with 100 % CPU and up to 16 GB of RAM. (Why not more, i have 32 GB?)
- At ~17 % the RAM stucks at 16 GB and the SDD kicks in ~400 - 700 MB/s, while the CPU goes back to 25 - 35 %
- The speed is noticeably slower now as it reached 17 % in under 5 minutes and now it takes minutes to show any new progress on 'bytes' and 'funcs' to increase further.
- after 15 - 20 minutes with no big progress (still at 17 %) it displays 'killed' and stops the execution or shows no progress at all and i stop it
- Thats the console output:
```
root@ff4d055c382e:/program# partition --serialize=file.ser --maximum-memory=128000 --no-semantics file.exe
OPTI[INFO ]: Analyzing executable: file.exe
PRT2[MARCH]: cfg:  17% [###------------] 3948124 bytes 250258 blks 1016 funcsKilled
```

**Comment by YamamotoKaderate** [comment]
I didn't kept track of all my trials and error but I had the same problem. 
By default, wsl limit the memory usage to 50% of your RAM (it must be the same for SWAP), hence the swap limit redefinition in wslconfig.
Your 245GB limit is probably ignored and the kernel is probably trying to free/allocate memory for your process until it is killed by the OOM killer (https://stackoverflow.com/questions/624857/finding-which-process-was-killed-by-linux-oom-killer )
Check your newline caracters in your .wslconfig (It should be linux LF, not windows CRLF)
Check https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/
Also, I had to reinstall docker (but maybe because I moved my swap file to another disk)

**Comment by Maxxxel** [comment]
I tried everything you mentioned... even recreated it completely. It totally ignores my settings int he file..

**Comment by sei-ccohen** [comment]
We haven't responded to this ticket because the problem mostly seems to be in the system configuration for RAM/swap.  A 26 MB executable is quite large, and this is definitely going to require a LOT of RAM to partition (and probably to analyze as well).   Other users running in cloud services have reported that ridiculously large amounts of swap do perform reasonably well because ROSE usually allocates memory for each function, and then doesn't really need to page the RAM back in very often.  Hopefully you'll be able to configure the swap or find a larger system.

**Comment by Maxxxel** [comment]
@sei-ccohen No Problem. The exe was Battleforge.exe and I've seen 2 years ago you've been in contact with other people for the same goal. And you provided a finished .json in an old issue. So my project is finished for now. Maybe I'll come back to the tool in the future but right now I can close this issue even tho I haven't solved it.

Thank you 🤞
