### ISSUE TITLE
Suboptimal build configuration

### ISSUE THREAD

**Issue by v-p-b** [cmu-sei/pharos#27]
There is [this line](https://github.com/cmu-sei/pharos/blob/master/scripts/build.bash#L7) in `build.bash` : 

```sh
NCPU="${NCPU:-1}"
```

I'm no bash expert, but I noticed that building the Docker container didn't fully utilize my CPU, so I did a test:

```
$ echo "${NCPU:-1}"
1
```

Based on [this comment](https://github.com/cmu-sei/pharos/issues/16#issuecomment-503305896) (and reason) `NCPU` is supposed to be set to -1, but as you can see above, it is set to 1 instead. [This SO answer](https://stackoverflow.com/a/12691027) also confirms that the above code is semantically incorrect. The following code gives the expected result on my system (note the double dash):

```
$ echo "${NCPU:--1}"
-1
```

**Comment by edmcman** [comment]
The intended default is to use one CPU, since building with one CPU already requires a great deal of memory.  You can override this by setting NCPU to an appropriate value; the easiest way of doing this is probably to modify the Dockerfile, or just hardcoding the value of NCPU in `build.bash`, which you probably already figured out.

**Comment by v-p-b** [comment]
I'm a bit confused. The linked comment states this (emphasis mine): 

"Actually, the build.bash script defaults to _NCPU=-1_, which might result in _parallel builds_" 

As you can see, this is not the case. I assume (and I can be wrong here, as the man page is unclear about this) that `make -j -1` in the later parts of the build script will let it use all cores. This would make sense to me, because this can greatly improve build time, and RAM is cheap.

If this is intended behavior, feel free to close the issue of course.

**Comment by sei-ccohen** [comment]
The comment that you linked to was from me, and I was wrong. ;-)  Ed commented somewhat cryptically: 
 
 @sei-ccohen Try echo ${NCPU:-1} :)

Which I did and found that it sets NCPU to one, which is what Ed intended (but not what I or apparently you expected)  Ed did that because it increases the memory requirements for the build by approximately a multiple of the number of CPUs used, and as the other issue points out, most people don't have sufficient RAM allocated with even one CPU.  While RAM _is_ cheap, and we frequently build with -j32, the majority of our public build problem reports have been related to a shortage of RAM.

**Comment by v-p-b** [comment]
Ah, OK! I'd only add that maybe a word about this in INSTALL.md would be nice for the RAM-Bourgeoisie ;)
