### ISSUE TITLE
Import into eclipse

### ISSUE THREAD

**Issue by james-tate** [cmu-sei/pharos#29]
The *GhidraDev* plugin does not have an import option for the project. Eclipse does not recognize the plugin directory as a project. How are you importing this into Eclipse to build the plugin?

**Comment by sei-jgennari** [comment]
The plugin was created as a standard GhidraDev module project. You will probably need to create a new module project in Eclipse using the GhidraDev plugin and then add the java files in the OOAnalyzerPlugin src and ghidra_scripts directories (strictly speaking you only need the java files in the src directory).

**Comment by sei-ccohen** [comment]
We've avoided providing too much detail about how to build a Ghidra extension because we're not experts in Ghidra, and didn't want to be offering incorrect advice.  The closest thing that we've found to authoritative guidance on how to build Ghidra extensions is the [Ghidra Advanced Development Course](http://ghidra.re/courses/GhidraClass/AdvancedDevelopment/GhidraAdvancedDevelopment_withNotes.html).  Hopefully that provides what you need.  If not, you can reopen this issue or a new one, with a more specific question.
