### ISSUE TITLE
Some polymorphic calls are not recognizable

### ISSUE THREAD

**Issue by lcytxw** [cmu-sei/pharos#31]
When I test file /pharos/src/oo.cpp, OOAnalyzer unable to recognize some calls to vtable functions.More specifically,

![image](https://user-images.githubusercontent.com/31504275/62432195-fcf26c00-b760-11e9-957a-56c1b4007397.png)
![image](https://user-images.githubusercontent.com/31504275/62432223-1eebee80-b761-11e9-8d28-60792a458ad5.png)

Calls e->func3(), e->func4() and f->func1() not recognized by OOAnalyzer cause the config file seems like below:

![image](https://user-images.githubusercontent.com/31504275/62432319-9d489080-b761-11e9-9f88-8e7b9e243f91.png)
Only vcall e->func1() can be recognized.

**Comment by sei-ccohen** [comment]
Thanks for this bug report.   It looks like the problem is related to the JSON exporter, not the actual [Prolog results](https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/tests/ooex_vs2008/Debug/oo.results#L44), which is good news, because detection problems are usually harder to fix than reporting problems.  It will probably take us a while to fix this, but it's on the list now.

**Comment by lcytxw** [comment]
Thank you. This work is really meaningful.

**Comment by sei-ccohen** [comment]
Just adding additional notes about this bug to make it clearer what the problem is.   The JSON results for ooex_vs2008/Debug/oo.exe report:

  "Vcalls": [{ "call": "4116a2", "targets": [{ "ea": "411970" }]}]

But the Prolog results for the same file are:

finalResolvedVirtualCall(0x4116a2, 0x417824, 0x411970).
finalResolvedVirtualCall(0x4116bb, 0x417814, 0x4119f0).
finalResolvedVirtualCall(0x4116d5, 0x417814, 0x4118f0).
finalResolvedVirtualCall(0x4116ea, 0x417824, 0x411970).

So it appears that perhaps our JSON reporter only ever reports the first virtual call?

**Comment by jeffgennari** [comment]
The code to pull out virtual function call targets examines call descriptors. which apparently do not account for multiple targets: https://github.com/cmu-sei/pharos/blob/747576fb42409916437c14b189a61b37d714bb8d/libpharos/oojson_exporter.cpp#L433

**Comment by Trass3r** [comment]
Indeed I got 52 finalResolvedVirtualCall's in another test (from different callsites) but only a single VCalls entry in the entire json file.
