### ISSUE TITLE
Mach-O x86_64 Support?

### ISSUE THREAD

**Issue by karanlyons** [cmu-sei/pharos#49]
```
# ooanalyzer --allow-64bit macho_binary --json macho_binary.json
OPTI[INFO ]: Analyzing executable: macho_binary
OPTI[INFO ]: OOAnalyzer version 1.0.
OOAN[FATAL]: Pharos main error: unrecognized file format for "macho_binary": Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>
```

It’s not clear to me from the documentation I can find whether or not macOS binaries are meant to be supported, or whether or not I’m doing something wrong. Are they? Am I?

**Comment by edmcman** [comment]
OOAnalyzer only supports Windows PE files right now.

We would welcome a pull request that extends support to Mac binaries, but we have no plans to implement this ourselves right now.  If you would be interested in implementing this, let us know.  We're helping some other researchers add support for Linux binaries and can guide you through the process.

**Comment by karanlyons** [comment]
I haven’t the bandwidth to tackle this myself right now, but it’s possible that once support for ELF binaries lands we can reuse much of the added scaffolding to support Macho-O as well.

**Comment by sei-eschwartz** [comment]
That sounds like a good plan.  At the very least, once we add support for ELF/Linux, it should be clear what types of changes need to be made for a new platform.

**Comment by sei-ccohen** [comment]
Actually, the real problem is that ROSE doesn't currently support the Mach-O executable container file-format.  If you look at the this [documentation](http://rosecompiler.org/ROSE_HTML_Reference/classSgAsmGenericHeader.html) you will see that while there is support (derived classes in the diagram) for ELF, PE, LE, NE, and DOS, but there's no support for Mach-O.   I've raised this issue with the ROSE developers and they're aware of it, and just haven't been able to allocate resources to correct it.   Chances are pretty good that if we had an executable file format container parser for Mach-O, it would work just as well as we support GCC or Clang on Linux...  Which is to say not very well at present. :-(  But the good news is that from that once GCC worked on ELF, it would probably just work on Mach-O as well then (or at least be really close).   I actually think the Mach-O container support is the smaller problem compared to 64-bit Linux/GCC support in OOAnalyzer.

**Comment by sei-eschwartz** [comment]
Closing this since it won't realistically be fixed anytime soon.
