### ISSUE TITLE
switch table confused as function start

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#52]
https://godbolt.org/z/4yL7RO

```cpp
// cl -nologo -O2 -GS- -Gy- -Z7 main.cpp -MD -link /opt:ref
struct A
{
	int b = 4;
	int foo(int num);
	int bar(int a);
};

int A::foo(int num)
{
	switch (num)
	{
	case 0:
	case 1:
	case 12:
	case 3:
	case 22:
	case 13:
	case 20:
		return num;
		break;
	case 8:
	case 11:
	case 17:
	case 4:
	case 10:
		return num;
		break;
	}
	return num * num;
}
int A::bar(int a) { return b * a; }
int main(int argc, const char* argv[]) { return ((A*)argv)->foo(5); }
```

Produces a switch table between foo and bar.
```asm
.text:00401028                 db      0,     1,     0
.text:0040103F                 align 10h
.text:00401040 A::bar       proc
```
But bar is recognized by pharos as starting at offset 40103c.

**Comment by sei-ccohen** [comment]
Interesting test case.  I think the explanation of the behavior goes something like this...  The function bar is not called from anywhere, so the partitioner must make some guesses to discover it.  The "align 10h" at 0x40103F is probably actually some form of NOP instruction, although I've not actually confirmed this.  Then when we come to the unknown "data block" beginning around 0x040102B(?), we attempt to make code, which succeeds in creating something vaguely "bar-like" but at the wrong address.   We would get better results if bar() was actually called from somewhere.   Arguably, if bar() is not called from anywhere, is there really a function there?  Obviously there is, but it's also not too surprising that it's hard to find correctly. :-)

**Comment by Trass3r** [comment]
Just a reduced test case, in the original code it's probably used. But may have been virtual functions.

**Comment by sei-ccohen** [comment]
I was going to say "called or used in a virtual function table", but then I realized that the partitioner doesn't really know about virtual function tables, so the problem will persist when the only reference to the function is in a virtual table and it is not called directly elsewhere.  :-(   The fix for that problem is much more complicated, and involves freeing our framework from the idea that partitioning occurs _before_ analysis, and shifting to a model where partitioning occurs _during_ analysis.   Sadly, that's not likely to happy any time soon...
