### ISSUE TITLE
Duplicate merging of classes

### ISSUE THREAD

**Issue by Phylante** [cmu-sei/pharos#58]
**Background information:**
I am processing a 7 MB file. Around 68k functions.
I serialized the partitioning on a server, using 72 threads; then took the 12GB file to another server and resumed from here (using 1 core as the analysis can't be parallel).
Before canceling ooanalyzer on that first server, it was using 140GB of ram (was my limit). On the second server, I set no limit, using a 300GB swap, but is currently using only 47GB of ram (does the first pass does not release memory correctly or is it related to threads? But that's not my issue here)
I am using the eschwartz/pharos docker image with tag 089f94992923 from 3 or 4 weeks ago.
It has been processing for around 14 days at the moment.

**Issue:**
Even if it seems like I can't set the log level greater than 4 (crashes, can't remember failure, but can find it if needed), logs display the merging of classes.
I can see that some classes are merged into the same other one a couple of time. *I am wondering if this is a wanted behavior or not.*

You can check the attached log and look for the string "Merging class 0x71ad00 into 0x854be0" and see that it happened 10 times these last 5 days.

[logs_ooanalyzer.txt](https://github.com/cmu-sei/pharos/files/3884109/logs_ooanalyzer.txt)

**Comment by sei-eschwartz** [comment]
Try using the `seipharos/pharos` docker image.  `edmcman/pharos` was last updated 4 months ago.  Since then, we've fixed some major memory issues.

Although this wasn't what you were asking about, I've been working with the developers of XSB and SWI prolog to improve our Prolog performance.  This hasn't officially been added to the repository, but you can try out this branch: https://github.com/edmcman/pharos/tree/swi-new  Maybe it will help speed things up for you.

About your actual question, seeing such messages repeated is normal.  At a high level, OOAnalyzer made a few guesses:

```
2019-11-20T07:39:28.218917211Z 807216.64851s PLOG[INFO ]: Guessing factVFTableEntry(0x98546c, 0x4, 0x51e040).
2019-11-20T07:39:28.219119931Z 807216.64863s PLOG[INFO ]: Guessing factVFTableEntry(0x96c474, 0x18, 0x5472e0).
2019-11-20T07:39:28.219131267Z 807216.64874s PLOG[INFO ]: Guessing factVFTableEntry(0x977478, 0x4, 0x66e2a0).
2019-11-20T07:39:28.219171817Z 807216.64886s PLOG[INFO ]: Guessing factVFTableEntry(0x985478, 0x68, 0x854df0).
```

Although it couldn't tell at that point in time, after forward reasoning it was able to detect a contradiction:
```
2019-11-20T19:14:05.603422631Z 848894.03301s PLOG[WARN ]: failed.
2019-11-20T19:14:05.603515852Z 848894.03307s PLOG[WARN ]: Consistency checks failed.
2019-11-20T19:14:05.603524571Z 848894.03313s PLOG[WARN ]: Contradictory information about merging classes: Method1=0x854be0 Method2=0x59bf50
2019-11-20T19:14:05.706176610Z 848894.13582s PLOG[WARN ]: Constraint checks failed, retracting guess!
```

It then does binary search to try to identify which guess was the bad one.  Because of this retraction, the same guess can be made several times, and the conclusions of that guess can be processed several times as well.  This includes class merging.

Since this isn't a bug, I'm going to close the issue.  If the log level isn't working properly, please create a new issue for that!

**Comment by Phylante** [comment]
Thanks for your answer.
I'll try the seipharos/pharos image and the swinew branch. 
Please note that I wasn't mentioning the docker image from ecdmcman, but yours : eschwarz/pharos.

**Comment by sei-eschwartz** [comment]
Sorry, I meant `eschwartz/pharos`.  `edmcman` is another username I use.
