### ISSUE TITLE
Warnings about missing return values followed by prolog warning

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#87]
After adding the JSON file that defines the MFC42 function calls, these calls get demangled etc properly. However, much further on I am presented with numerous new warnings and finally a warning by the prolog analysis:

```
[ .. many more 'Missing return value'.. ]

OOAN[ERROR]: Missing return value from new() call at 0x006A216C
OOAN[ERROR]: Missing return value from new() call at 0x006A23E3
OPTI[MARCH]: Prolog facts: [-----#####-----] 149470Warning: In assert to trigger_fact/1, an index hash chain is very long; consider using asserta, multi or no index.
```
and the program in deed takes much longer to finish. In fact, it has not finished in several days on the machine I am using - but that does not mean anything is going wrong, of course. Maybe the MFC definitions simply provide a lot more information to crunch through.

Still, I thought it might be good to ask here if this is expected behavior.

Thanks,

Jan

**Comment by sei-eschwartz** [comment]
@sei-ccohen should be able to explain what the missing return value warning means.

As for the longer run time, it probably does mean that there is more analysis happening.  I also have a run going that is using our own API data for MFC42, and it too has been running multiple days, whereas a run without the MFC42 data completed already.  You could run the Prolog step using SWI Prolog which we've found to be a lot faster, but as of right now we don't have a way to get the JSON output for the plugin from SWI.  We're actively working on getting that working...  Anyway, for now the best advice is probably to be patient :-(

**Comment by sei-ccohen** [comment]
Unfortunately, the error is difficult to understand completely, which is why it continues to get emitted occasionally rather than just getting fixed. :-( The error is generated [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L574), where the context is that a call instruction (to new) did not have a proper return value.    It's only ever set from [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/defuse.cpp#L947) which is turn called from a limited range of lines (1078-1116) in the same file.

The call was supposed to have been evaluated, and a return value set during analysis of the function that contained it.  There are a multitude of reasons why the return value might not be set, including: analysis of the function containing the call timed out, the stack deltas in the function were wrong and parameter analysis got confused,  the call wasn't in the control flow and therefore wasn't evaluated, there's some other bug, etc.  Particularly in 32-bit windows code, a large number of things have to have worked correctly for this code to work.  These errors (along with your increased run-time) are almost certainly a result of improved API data providing better stack delta analysis, which in turn allowed more calls to be analyzed, which ultimately resulted in this error.

I've looked at several of these in the past, and it's always been some other reason that was difficult to fix or understand.  My recollection is that the underlying root causes varied quite a bit.  In one case I'm fairly certain it was caused by some unusual function prologue behavior.   Since we also have the file that caused the problems, I may be able to investigate some more, but given the history of this error, I can't promise much.

**Comment by sei-ccohen** [comment]
Oh, and the strange error from Prolog about the index hash chain being too long is apparently something that you can just ignore.   I'm not certain why XSB Prolog feels like telling us that is helpful.   As far as I can tell it means "Wow, you've got a lot of facts!"

**Comment by sei-eschwartz** [comment]
My run with the MFC data did eventually complete.  Did yours?

**Comment by janbbeck** [comment]
I just stopped the run a couple of hours ago ... I wish I had known yours finished :/
The computer had gotten annoyingly unresponsive due to paging. Going to restart tomorrow on a machine with a little more ram (64gb vs 40gb)

**Comment by janbbeck** [comment]
> Unfortunately, the error is difficult to understand completely, which is why it continues to get emitted occasionally rather than just getting fixed. :-( The error is generated [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L574), where the context is that a call instruction (to new) did not have a proper return value. It's only ever set from [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/defuse.cpp#L947) which is turn called from a limited range of lines (1078-1116) in the same file.
> 
> The call was supposed to have been evaluated, and a return value set during analysis of the function that contained it. There are a multitude of reasons why the return value might not be set, including: analysis of the function containing the call timed out, the stack deltas in the function were wrong and parameter analysis got confused, the call wasn't in the control flow and therefore wasn't evaluated, there's some other bug, etc. Particularly in 32-bit windows code, a large number of things have to have worked correctly for this code to work. These errors (along with your increased run-time) are almost certainly a result of improved API data providing better stack delta analysis, which in turn allowed more calls to be analyzed, which ultimately resulted in this error.
> 
> I've looked at several of these in the past, and it's always been some other reason that was difficult to fix or understand. My recollection is that the underlying root causes varied quite a bit. In one case I'm fairly certain it was caused by some unusual function prologue behavior. Since we also have the file that caused the problems, I may be able to investigate some more, but given the history of this error, I can't promise much.

Thank you for that detailed explanation!

I certainly have some functions that don't get analyzed due to the timing/memory limits. I will try to make sure they all get the time they deserve before looking at anything else.

I would like to point out that the error messages could be more useful. Currently, I use `--timeout  --maximum-memory`  and `--partitioner-timeout`. And I only found those parameters by googling around and found that someone else had the exact same problem in a previous github issue that is now closed. To a new user it is unclear what the difference is between the two timeout parameters. Worse, one does not know which one the error message is referring to: `FSEM[ERROR]: Analysis of function 0x0041D630 failed: relative CPU time exceeded`
My current understanding is the `--timeout` is a `total-program-timeout` and `--partitioner-timeout` is a `per-function-timeout` - i.e. the relative timeout.

I think it would be an improvement if the error message said:
`FSEM[ERROR]: Analysis of function 0x0041D630 failed: relative CPU time exceeded -- try to increase the --partitioner-timeout parameter to ooanalyzer`
and similarly for the memory limit.

In general, I would humbly suggest to just remove the limits by default and just let the user add limits when there is a problem that needs them.

**Comment by sei-eschwartz** [comment]
I like the idea of saying which setting can be adjusted in the warning message itself.  As a case in point, `--partitioner-timeout` is now unlimited by default, and is not the `per-function-timeout`.  `--per-function-timeout` controls the `per-function-timeout`.

**Comment by sei-eschwartz** [comment]
By the way, here is the JSON I had for the run with MFC.  I don't remember what version I was using, so it may be incompatible with the version on github.  But I figured I would share it in case you want to try it.
[V9.zip](https://github.com/cmu-sei/pharos/files/4662602/V9.zip)

**Comment by janbbeck** [comment]
Thanks for that. I am currently running ooanalyzer again with what I hope is unlimited timing/memory settings and json files for `mfc42.dll`, `winmm.dll`, `setupapi.dll` and `winspool.dll`
I'll post the json files here if it looks like they are correct.
