### ISSUE TITLE
How do I add optional dll json files?

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#89]
Since there is the '--apidb' switch, there is really no reason to not offer optional library support that is not present in the standard DB.
This way, a user can just add '--apidb setupapi.json --apidb winmm.json' etc. as necessary.

As you can see here, 
![Screenshot from 2020-05-25 19-26-01](https://user-images.githubusercontent.com/11450961/82873993-03471400-9f3e-11ea-97bf-08683af6f985.png)

ooanalyzer expects these files to be in `/usr/local/share/pharos` instead of `/usr/local/share/pharos/apidb`
Where in the github hierarchy should these go? In `pharos/share` where `apidb` resides?

**Comment by sei-eschwartz** [comment]
We are still thinking about how this will work.  But for now, I would put the files inside the `apidb` directory.  They can be specified by full path.  Or you could modify the code that handles the `--apidb` option to search for files in the `apidb` directory by default.

**Comment by sei-mwd** [comment]
Looking into this I have found a small misfeature in the lookup of API databases that I will fix for the next version, but it is not a misfeature being triggered by your example above.

To explain: when presented with a relative path, apidb will look for that relative pathname from the context of the library directory, which, when installed at `$PREFIX`, will be `$PREFIX/share/pharos`.  The built-in databases are part of the config, which we can determine using `--dump-config`:

    $ ./apilookup --dump-config | grep apidb
      apidb: [apidb/pharos-api-additions.json, apidb/pharos-apidb.sqlite]

The code acts as if the arguments to `--apidb` are prepended to this list.  So, if you want to install new files in the `apidb` directory, you'll have to use `--apidb=apidb/myfile.json`.

The reason that the library directory is used as the base for lookup rather than the `apidb` directory is historical.  Before I rewrote the API DB code to handle SQLite and JSON, there existed a DB that was only JSON files.  The files were in `share/pharos/config` (the name, once again, for historical reasons), and they had names of the form _&lt;dllname&gt;_`.json`.  Before we moved away from these completely, there was an entry, `config`, in the config clause.  The API DB code, when receiving a directory name as an entry, will use the DLL names as keys to look up files in that directory.  In your case, you may want to use that feature yourself, as the code should still work.

The misfeature I mention at the beginning is that if you pass `--apidb` a value of, say, `./foo.json`, this is still a relative name, and it will look it up from the library directory.  I think that this would be surprising to the user, so I will be fixing that.

**Comment by sei-mwd** [comment]
Oh, right.  If you are building a modified pharos and want these DBs to always be available, put them in share/aidb and modify the `apidb` clause in `libpharos/config.yaml.in` to match.

**Comment by janbbeck** [comment]
Thank you all for these comments. I have been using full path on my end, and that is fine for me.
I have reopened my pull request  #88 putting the json files in apidb, because that is where I think they should live.

**Comment by sei-mwd** [comment]
Merged #88
